# Generated by Django 3.1.4 on 2021-01-01 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='reviews',
            name='applauds',
            field=models.ManyToManyField(blank=True, related_name='collected_applauds', to=settings.AUTH_USER_MODEL),
        ),
    ]
